/**
 * OpenSCAP Report Parser
 * Parses both XCCDF/ARF XML and HTML reports generated by OpenSCAP
 */

const OpenSCAPParser = (() => {
  // XCCDF namespaces
  const NS = {
    xccdf12: 'http://checklists.nist.gov/xccdf/1.2',
    xccdf11: 'http://checklists.nist.gov/xccdf/1.1',
    arf: 'http://scap.nist.gov/schema/asset-reporting-format/1.1',
    oval: 'http://oval.mitre.org/XMLSchema/oval-results-5',
  };

  /**
   * Detect file type and parse accordingly
   * @param {string} content - file content
   * @param {string} filename - original filename
   * @returns {object} parsed report
   */
  function parse(content, filename) {
    const trimmed = content.trim();
    if (trimmed.startsWith('<?xml') || trimmed.startsWith('<Benchmark') || trimmed.startsWith('<asset-report-collection') || trimmed.startsWith('<cdf:Benchmark') || trimmed.startsWith('<ds:data-stream')) {
      return parseXML(content, filename);
    } else if (trimmed.startsWith('<!DOCTYPE html') || trimmed.startsWith('<html') || trimmed.startsWith('<!doctype html')) {
      return parseHTML(content, filename);
    }
    // Try XML first, fallback to HTML
    try { return parseXML(content, filename); } catch (e) {
      try { return parseHTML(content, filename); } catch (e2) {
        throw new Error('Unable to parse file: not a recognized OpenSCAP report format');
      }
    }
  }

  // ─────── XML PARSING ───────

  function parseXML(content, filename) {
    const parser = new DOMParser();
    const doc = parser.parseFromString(content, 'application/xml');
    if (doc.querySelector('parsererror')) {
      throw new Error('Invalid XML: ' + doc.querySelector('parsererror').textContent.substring(0, 200));
    }

    // Detect namespace
    const ns = detectNamespace(doc);
    const isARF = !!doc.querySelector('asset-report-collection') ||
                  doc.documentElement.namespaceURI === NS.arf ||
                  doc.documentElement.localName === 'asset-report-collection';

    // Find Benchmark and TestResult
    let benchmark, testResult;
    if (isARF) {
      benchmark = queryNS(doc, 'Benchmark', ns);
      testResult = queryNS(doc, 'TestResult', ns);
    } else {
      benchmark = doc.documentElement.localName === 'Benchmark' ? doc.documentElement : queryNS(doc, 'Benchmark', ns);
      testResult = queryNS(doc, 'TestResult', ns);
    }

    if (!testResult) throw new Error('No TestResult found in XML');

    const report = {
      source: 'xml',
      sourceType: isARF ? 'ARF' : 'XCCDF',
      filename: filename,
      metadata: extractXMLMetadata(testResult, benchmark, ns),
      rules: extractXMLRuleResults(testResult, benchmark, ns),
    };

    // Calculate stats
    report.stats = calculateStats(report.rules);
    return report;
  }

  function detectNamespace(doc) {
    // Check root element namespace
    const root = doc.documentElement;
    if (root.namespaceURI === NS.xccdf12) return NS.xccdf12;
    if (root.namespaceURI === NS.xccdf11) return NS.xccdf11;
    // Check for Benchmark in either namespace
    if (doc.getElementsByTagNameNS(NS.xccdf12, 'Benchmark').length > 0) return NS.xccdf12;
    if (doc.getElementsByTagNameNS(NS.xccdf11, 'Benchmark').length > 0) return NS.xccdf11;
    // Check for TestResult
    if (doc.getElementsByTagNameNS(NS.xccdf12, 'TestResult').length > 0) return NS.xccdf12;
    if (doc.getElementsByTagNameNS(NS.xccdf11, 'TestResult').length > 0) return NS.xccdf11;
    // Fallback: try without namespace
    return null;
  }

  function queryNS(parent, localName, ns) {
    if (ns) {
      const els = parent.getElementsByTagNameNS(ns, localName);
      return els.length > 0 ? els[0] : null;
    }
    return parent.querySelector(localName) || parent.getElementsByTagName(localName)[0] || null;
  }

  function queryAllNS(parent, localName, ns) {
    if (ns) return Array.from(parent.getElementsByTagNameNS(ns, localName));
    return Array.from(parent.querySelectorAll(localName));
  }

  function getTextNS(parent, localName, ns) {
    const el = queryNS(parent, localName, ns);
    return el ? el.textContent.trim() : '';
  }

  function extractXMLMetadata(testResult, benchmark, ns) {
    const meta = {
      target: getTextNS(testResult, 'target', ns),
      targetAddresses: queryAllNS(testResult, 'target-address', ns).map(el => el.textContent.trim()),
      benchmarkHref: '',
      benchmarkId: '',
      benchmarkTitle: '',
      benchmarkVersion: '',
      profileId: '',
      profileTitle: '',
      startTime: testResult.getAttribute('start-time') || '',
      endTime: testResult.getAttribute('end-time') || '',
      testSystem: testResult.getAttribute('test-system') || '',
      identity: getTextNS(testResult, 'identity', ns),
      testResultId: testResult.getAttribute('id') || '',
      platforms: [],
      scores: [],
      targetFacts: {},
    };

    // Benchmark ref in TestResult
    const bmRef = queryNS(testResult, 'benchmark', ns);
    if (bmRef) {
      meta.benchmarkHref = bmRef.getAttribute('href') || '';
      meta.benchmarkId = bmRef.getAttribute('id') || '';
    }
    if (benchmark) {
      meta.benchmarkTitle = getTextNS(benchmark, 'title', ns);
      meta.benchmarkVersion = getTextNS(benchmark, 'version', ns);
      if (!meta.benchmarkId) meta.benchmarkId = benchmark.getAttribute('id') || '';
    }

    // Profile
    const profileRef = queryNS(testResult, 'profile', ns);
    if (profileRef) {
      meta.profileId = profileRef.getAttribute('idref') || '';
      if (benchmark) {
        const profiles = queryAllNS(benchmark, 'Profile', ns);
        const matchedProfile = profiles.find(p => p.getAttribute('id') === meta.profileId);
        if (matchedProfile) {
          meta.profileTitle = getTextNS(matchedProfile, 'title', ns);
        }
      }
    }

    // Platforms
    meta.platforms = queryAllNS(testResult, 'platform', ns).map(el => el.getAttribute('idref') || el.textContent.trim());

    // Scores
    queryAllNS(testResult, 'score', ns).forEach(el => {
      meta.scores.push({
        system: el.getAttribute('system') || 'default',
        value: parseFloat(el.textContent) || 0,
        maximum: parseFloat(el.getAttribute('maximum')) || 100,
      });
    });

    // Target facts
    const factsContainer = queryNS(testResult, 'target-facts', ns);
    if (factsContainer) {
      queryAllNS(factsContainer, 'fact', ns).forEach(el => {
        const name = el.getAttribute('name') || '';
        meta.targetFacts[name] = el.textContent.trim();
      });
    }

    return meta;
  }

  function extractXMLRuleResults(testResult, benchmark, ns) {
    const ruleResults = queryAllNS(testResult, 'rule-result', ns);
    const rules = [];

    // Build rule info map from Benchmark if available
    const ruleInfoMap = {};
    if (benchmark) {
      queryAllNS(benchmark, 'Rule', ns).forEach(ruleEl => {
        const id = ruleEl.getAttribute('id') || '';
        
        let groupTitle = 'Other';
        let parent = ruleEl.parentNode;
        while (parent && parent.nodeType === 1) {
          if (parent.localName === 'Group') {
            groupTitle = getTextNS(parent, 'title', ns) || groupTitle;
            break;
          }
          parent = parent.parentNode;
        }

        ruleInfoMap[id] = {
          title: getTextNS(ruleEl, 'title', ns),
          description: getTextNS(ruleEl, 'description', ns),
          rationale: getTextNS(ruleEl, 'rationale', ns),
          severity: ruleEl.getAttribute('severity') || '',
          fixtext: getTextNS(ruleEl, 'fixtext', ns),
          groupTitle: groupTitle,
          idents: queryAllNS(ruleEl, 'ident', ns).map(el => ({
            system: el.getAttribute('system') || '',
            text: el.textContent.trim()
          })),
          references: queryAllNS(ruleEl, 'reference', ns).map(el => ({
            href: el.getAttribute('href') || '',
            text: el.textContent.trim()
          })),
        };
      });
    }

    ruleResults.forEach(rr => {
      const idref = rr.getAttribute('idref') || '';
      const result = getTextNS(rr, 'result', ns);
      const resultLower = result.toLowerCase();

      // Skip 'notselected' rules — these aren't part of the chosen profile
      // and inflate the rule count (e.g. 1530 total vs 292 selected)
      if (resultLower === 'notselected') return;

      const severity = rr.getAttribute('severity') || '';
      const time = rr.getAttribute('time') || '';

      const info = ruleInfoMap[idref] || {};
      const messages = queryAllNS(rr, 'message', ns).map(el => ({
        severity: el.getAttribute('severity') || '',
        text: el.textContent.trim()
      }));

      // Check for override/waiver
      const overrides = queryAllNS(rr, 'override', ns).map(el => ({
        authority: el.getAttribute('authority') || '',
        date: el.getAttribute('date') || '',
        oldResult: getTextNS(el, 'old-result', ns),
        remark: getTextNS(el, 'remark', ns),
      }));

      rules.push({
        idref,
        result: resultLower,
        severity: (severity || info.severity || 'unknown').toLowerCase(),
        time,
        title: info.title || idref.replace(/^xccdf_org\.ssgproject\.content_rule_/, '').replace(/_/g, ' '),
        groupTitle: info.groupTitle || 'Other',
        description: info.description || '',
        rationale: info.rationale || '',
        fixtext: info.fixtext || '',
        idents: info.idents || [],
        references: info.references || [],
        messages,
        overrides,
      });
    });

    return rules;
  }

  // ─────── HTML PARSING ───────

  function parseHTML(content, filename) {
    const parser = new DOMParser();
    const doc = parser.parseFromString(content, 'text/html');

    const report = {
      source: 'html',
      sourceType: 'HTML Report',
      filename: filename,
      metadata: extractHTMLMetadata(doc),
      rules: extractHTMLRuleResults(doc),
    };

    report.stats = calculateStats(report.rules);
    return report;
  }

  function extractHTMLMetadata(doc) {
    const meta = {
      target: '',
      targetAddresses: [],
      benchmarkHref: '',
      benchmarkId: '',
      benchmarkTitle: '',
      benchmarkVersion: '',
      profileId: '',
      profileTitle: '',
      startTime: '',
      endTime: '',
      testSystem: '',
      identity: '',
      testResultId: '',
      platforms: [],
      scores: [],
      targetFacts: {},
    };

    // Title from page
    const titleEl = doc.querySelector('title');
    if (titleEl) {
      const titleText = titleEl.textContent;
      const idMatch = titleText.match(/^(.+?)\s*\|/);
      if (idMatch) meta.testResultId = idMatch[1].trim();
    }

    // Benchmark title
    const h2 = doc.querySelector('#introduction h2, #content > .row h2');
    if (h2) meta.benchmarkTitle = h2.textContent.trim();

    // Profile from blockquote mark
    const profileMark = doc.querySelector('#introduction mark, blockquote mark');
    if (profileMark) meta.profileTitle = profileMark.textContent.trim();

    // Characteristics table
    const charDiv = doc.getElementById('characteristics');
    if (charDiv) {
      const rows = charDiv.querySelectorAll('table tr');
      rows.forEach(row => {
        const th = row.querySelector('th');
        const td = row.querySelector('td');
        if (!th || !td) return;
        const label = th.textContent.trim().toLowerCase();
        const val = td.textContent.trim();
        if (label.includes('evaluation target') || label.includes('target')) meta.target = val;
        else if (label.includes('benchmark url')) meta.benchmarkHref = val;
        else if (label.includes('benchmark id')) meta.benchmarkId = val;
        else if (label.includes('benchmark version')) meta.benchmarkVersion = val;
        else if (label.includes('profile id')) meta.profileId = val;
        else if (label.includes('started at') || label.includes('start')) meta.startTime = val;
        else if (label.includes('finished at') || label.includes('end') || label.includes('finish')) meta.endTime = val;
        else if (label.includes('performed by') || label.includes('identity')) meta.identity = val;
        else if (label.includes('test system')) meta.testSystem = val;
        else if (label.includes('target id')) meta.targetFacts['urn:xccdf:fact:identifier'] = val;
      });
    }

    // IP addresses
    const addressItems = doc.querySelectorAll('#characteristics .list-group-item');
    addressItems.forEach(li => {
      const badge = li.querySelector('.label');
      const text = li.textContent.trim();
      if (badge) {
        const badgeText = badge.textContent.trim();
        if (badgeText === 'IPv4' || badgeText === 'IPv6') {
          meta.targetAddresses.push(text.replace(badgeText, '').trim());
        } else if (badgeText === 'MAC') {
          meta.targetFacts['urn:xccdf:fact:ethernet:MAC'] = text.replace('MAC', '').trim();
        }
      }
    });

    // CPE platforms
    const cpeItems = doc.querySelectorAll('#characteristics .label-success, #characteristics .label-default');
    cpeItems.forEach(el => {
      const t = el.textContent.trim();
      if (t.startsWith('cpe:')) meta.platforms.push(t);
    });

    // Scores
    const scoreTable = doc.querySelector('#compliance-and-scoring table');
    if (scoreTable) {
      const scoreRows = scoreTable.querySelectorAll('tbody tr');
      scoreRows.forEach(row => {
        const cells = row.querySelectorAll('td');
        if (cells.length >= 3) {
          meta.scores.push({
            system: cells[0].textContent.trim(),
            value: parseFloat(cells[1].textContent) || 0,
            maximum: parseFloat(cells[2].textContent) || 100,
          });
        }
      });
    }

    return meta;
  }

  function extractHTMLRuleResults(doc) {
    const rules = [];
    // From rule-overview table rows
    const leafRows = doc.querySelectorAll('tr.rule-overview-leaf');
    leafRows.forEach(row => {
      const className = row.className || '';
      // Extract result from class: rule-overview-leaf-pass, rule-overview-leaf-fail, etc.
      const resultMatch = className.match(/rule-overview-leaf-(pass|fail|error|unknown|fixed|informational|notchecked|notapplicable|notselected)/);
      const result = resultMatch ? resultMatch[1] : 'unknown';

      // Extract rule ID — prefer class-based ID (the real XCCDF rule ID)
      // data-tt-id is an internal treetable node ID, NOT the XCCDF rule ID
      let idref = '';
      const idMatch = className.match(/rule-overview-leaf-id-(xccdf_\S+)/);
      if (idMatch) {
        idref = idMatch[1];
      } else {
        // Fallback: try broader class match or data-tt-id
        const idMatch2 = className.match(/rule-overview-leaf-id-(\S+)/);
        if (idMatch2) idref = idMatch2[1];
        else idref = row.getAttribute('data-tt-id') || '';
      }

      // Title from link text
      const link = row.querySelector('td a');
      const title = link ? link.textContent.trim() : idref;

      // Severity from dedicated cell
      const severityCell = row.querySelector('td.rule-severity');
      const severity = severityCell ? severityCell.textContent.trim().toLowerCase() : 'unknown';

      // Also try to extract references from data-references attribute
      let references = [];
      const refsAttr = row.getAttribute('data-references');
      if (refsAttr) {
        try {
          const refsObj = JSON.parse(refsAttr);
          Object.entries(refsObj).forEach(([key, vals]) => {
            if (Array.isArray(vals)) {
              vals.forEach(v => references.push({ href: '', text: `${key}: ${v}` }));
            }
          });
        } catch (e) { /* ignore parse errors */ }
      }

      // Extract Group Title via treetable parent id
      let groupTitle = 'Other';
      const parentId = row.getAttribute('data-tt-parent-id');
      if (parentId) {
        // Find parent row using exact match (escaping any weird chars just in case)
        const parentRow = doc.querySelector(`tr[data-tt-id="${parentId}"]`);
        if (parentRow) {
          const firstTd = parentRow.querySelector('td');
          if (firstTd) {
            // Clone to remove labels/badges and scripts without affecting DOM
            const clone = firstTd.cloneNode(true);
            clone.querySelectorAll('.label, .badge, .indenter, script').forEach(el => el.remove());
            const text = clone.textContent.replace(/▼|►/g, '').trim();
            if (text) groupTitle = text;
          }
        }
      }

      if (idref) {
        rules.push({
          idref,
          result: result.toLowerCase(),
          severity,
          time: '',
          title: title || idref.replace(/^xccdf_org\.ssgproject\.content_rule_/, '').replace(/_/g, ' '),
          groupTitle: groupTitle,
          description: '',
          rationale: '',
          fixtext: '',
          idents: [],
          references,
          messages: [],
          overrides: [],
        });
      }
    });

    // If no overview rows found, try result-details panels
    if (rules.length === 0) {
      const panels = doc.querySelectorAll('.rule-detail');
      panels.forEach(panel => {
        const className = panel.className || '';
        const resultMatch = className.match(/rule-detail-(pass|fail|error|unknown|fixed|informational|notchecked|notapplicable|notselected)/);
        const result = resultMatch ? resultMatch[1] : 'unknown';

        let idref = '';
        const idRow = panel.querySelector('.rule-id');
        if (idRow) idref = idRow.textContent.trim();
        if (!idref) {
          const idMatch = className.match(/rule-detail-id-(\S+)/);
          if (idMatch) idref = idMatch[1];
        }

        const titleEl = panel.querySelector('.panel-title');
        const title = titleEl ? titleEl.textContent.trim() : idref;

        if (idref) {
          rules.push({
            idref,
            result: result.toLowerCase(),
            severity: 'unknown',
            time: '',
            title,
            groupTitle: 'Other',
            description: '',
            rationale: '',
            fixtext: '',
            idents: [],
            references: [],
            messages: [],
            overrides: [],
          });
        }
      });
    }

    return rules;
  }

  // ─────── STATS ───────

  function calculateStats(rules) {
    const total = rules.length;
    const pass = rules.filter(r => r.result === 'pass' || r.result === 'fixed').length;
    const fail = rules.filter(r => r.result === 'fail').length;
    const error = rules.filter(r => r.result === 'error' || r.result === 'unknown').length;
    const na = rules.filter(r => r.result === 'notapplicable' || r.result === 'notselected').length;
    const other = total - pass - fail - error - na;
    const applicable = total - na;
    const compliancePercent = applicable > 0 ? Math.round((pass / applicable) * 10000) / 100 : 0;

    return { total, pass, fail, error, na, other, applicable, compliancePercent };
  }

  return { parse, parseXML, parseHTML, calculateStats };
})();
